import type { Metadata } from "next";
import { Inconsolata, Roboto } from "next/font/google";
import "./globals.css";
import Header from "./components/organisms/Header";
import Footer from "./components/organisms/Footer";

const inconsolata = Inconsolata({
      variable: "--font-inconsolata",
      subsets: ["latin"],
});

const roboto = Roboto({
      variable: "--font-roboto",
      subsets: ["latin"],
});

export const metadata: Metadata = {
      title: "Create Next App",
      description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
      return (
            <html
                  lang="en"
                  className={`${inconsolata.variable} ${roboto.variable} text-black bg-cream h-full antialiased scroll-smooth`}
            >
                  <body className=" min-h-full flex flex-col">
                        <Header />
                        <main>
                              {children}
                        </main>
                        <Footer />
                  </body>
            </html>
      );
}
